import os

class Config(object):
    DYNAMODB_REGION = 'ap-northeast-1'
    SESSION_TYPE = 'dynamodb'
    SESSION_DYNAMODB_TABLE = 'serverless_blog_sessions'
    SESSION_DYNAMODB_REGION = DYNAMODB_REGION
    USERNAME = 'john'


class DevelopmentConfig(Config):
    DEBUG=True
    AWS_ACCESS_KEY_ID = 'aws123456789'
    AWS_SECRET_ACCESS_KEY = 'aws123456789'
    DYNAMODB_ENDPOINT_URL = 'http://localhost:8000'

    SECRET_KEY = '192b9bdd22ab9ed4d12e236c78afcb9a393ec15f71bbf5dc987d54727823bcbf'
    PASSWORD = 'due123'

    SESSION_DYNAMODB_KEY_ID =  AWS_ACCESS_KEY_ID
    SESSION_DYNAMODB_SECRET =  AWS_SECRET_ACCESS_KEY
    SESSION_DYNAMODB_ENDPOINT_URL =  DYNAMODB_ENDPOINT_URL

class ProductionConfig(Config):
    DEBUG=False
    AWS_ACCESS_KEY_ID = os.environ.get('SERVERLESS_AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('SERVERLESS_AWS_SECRET_KEY')
    DYNAMODB_ENDPOINT_URL = None

    SECRET_KEY = os.environ.get('SERVERLESS_SECRET_KEY')
    PASSWORD = os.environ.get('SERVERLESS_USER_PW')

    SESSION_DYNAMODB_KEY_ID =  AWS_ACCESS_KEY_ID
    SESSION_DYNAMODB_SECRET =  AWS_SECRET_ACCESS_KEY
    SESSION_DYNAMODB_ENDPOINT_URL =  DYNAMODB_ENDPOINT_URL